[package]
name = "ECC-Cache"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "distributed-cache-server"
path = "src/server_cli.rs"

[[bin]] 
name = "distributed-cache-client"
path = "src/client.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
futures = "0.3.4"
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.5"